#!/bin/bash 
git rm --cached RoadRad/src/scenes
git rm --cached RoadRad/src/scenes/.DS_Store
git rm --cached RoadRad/src/scenes/scene0
git rm --cached RoadRad/src/scenes/scene0/.DS_Store
git rm --cached RoadRad/src/scenes/scene0/.txt
git rm --cached RoadRad/src/scenes/scene0/0_ab_1000_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_ab_100_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_ab_10_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_ab_1_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_ambient_ad_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_ambient_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_av_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_dr_1_ab_1_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_dr_1_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_dv_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_modified_HPS_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_modified_HPS_test.pf
git rm --cached RoadRad/src/scenes/scene0/0_modified_HPS_test.txt
git rm --cached RoadRad/src/scenes/scene0/0_modified_LED_4000_pfilt_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_modified_LED_4000_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_modified_LED_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_modified_LED_test.pf
git rm --cached RoadRad/src/scenes/scene0/0_modified_LED_test.txt
git rm --cached RoadRad/src/scenes/scene0/0_modified_LPS_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_modified_LPS_test_old.hdr
git rm --cached RoadRad/src/scenes/scene0/0_modified_fluorsecent_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_modified_mercury_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_pcond_HPS.hdr
git rm --cached RoadRad/src/scenes/scene0/0_pcond_LED.hdr
git rm --cached RoadRad/src/scenes/scene0/0_pf.txt
git rm --cached RoadRad/src/scenes/scene0/0_pf_modified_test.hdr
git rm --cached RoadRad/src/scenes/scene0/0_standard_test.hdr
git rm --cached RoadRad/src/scenes/scene0/HellaEcoLight_1000lm_LDT.dat
git rm --cached RoadRad/src/scenes/scene0/HellaEcoLight_1000lm_LDT.ies
git rm --cached RoadRad/src/scenes/scene0/TX033306.ies
git rm --cached RoadRad/src/scenes/scene0/asd.txt
git rm --cached RoadRad/src/scenes/scene0/dashed_white.rad
git rm --cached RoadRad/src/scenes/scene0/ex2_old.dat
git rm --cached RoadRad/src/scenes/scene0/eye.vp
git rm --cached RoadRad/src/scenes/scene0/hdr2pf.py
git rm --cached RoadRad/src/scenes/scene0/light_pole.rad
git rm --cached RoadRad/src/scenes/scene0/lights_s.rad
git rm --cached RoadRad/src/scenes/scene0/luminaire.rad
git rm --cached RoadRad/src/scenes/scene0/luminaire.rad copy
git rm --cached RoadRad/src/scenes/scene0/luminaire_HPS.rad
git rm --cached RoadRad/src/scenes/scene0/luminaire_LED.rad
git rm --cached RoadRad/src/scenes/scene0/luminaire_LPS.rad
git rm --cached RoadRad/src/scenes/scene0/luminaire_fluorescent.rad
git rm --cached RoadRad/src/scenes/scene0/luminaire_mercury.rad
git rm --cached RoadRad/src/scenes/scene0/materials.rad
git rm --cached RoadRad/src/scenes/scene0/night_sky.rad
git rm --cached RoadRad/src/scenes/scene0/out_hr0.pic
git rm --cached RoadRad/src/scenes/scene0/out_hr1.pic
git rm --cached RoadRad/src/scenes/scene0/out_hr10.pic
git rm --cached RoadRad/src/scenes/scene0/out_hr11.pic
git rm --cached RoadRad/src/scenes/scene0/out_hr12.pic
git rm --cached RoadRad/src/scenes/scene0/out_hr13.pic
git rm --cached RoadRad/src/scenes/scene0/out_hr2.pic
git rm --cached RoadRad/src/scenes/scene0/out_hr3.pic
git rm --cached RoadRad/src/scenes/scene0/out_hr4.pic
git rm --cached RoadRad/src/scenes/scene0/out_hr5.pic
git rm --cached RoadRad/src/scenes/scene0/out_hr6.pic
git rm --cached RoadRad/src/scenes/scene0/out_hr7.pic
git rm --cached RoadRad/src/scenes/scene0/out_hr8.pic
git rm --cached RoadRad/src/scenes/scene0/out_hr9.pic
git rm --cached RoadRad/src/scenes/scene0/road.rad
git rm --cached RoadRad/src/scenes/scene0/scene0.oct
git rm --cached RoadRad/src/scenes/scene0/scene0_modified.oct
git rm --cached RoadRad/src/scenes/scene0/scene1.oct
git rm --cached RoadRad/src/scenes/scene0/scene10.oct
git rm --cached RoadRad/src/scenes/scene0/scene11.oct
git rm --cached RoadRad/src/scenes/scene0/scene12.oct
git rm --cached RoadRad/src/scenes/scene0/scene13.oct
git rm --cached RoadRad/src/scenes/scene0/scene2.oct
git rm --cached RoadRad/src/scenes/scene0/scene3.oct
git rm --cached RoadRad/src/scenes/scene0/scene4.oct
git rm --cached RoadRad/src/scenes/scene0/scene5.oct
git rm --cached RoadRad/src/scenes/scene0/scene6.oct
git rm --cached RoadRad/src/scenes/scene0/scene7.oct
git rm --cached RoadRad/src/scenes/scene0/scene8.oct
git rm --cached RoadRad/src/scenes/scene0/scene9.oct
git rm --cached RoadRad/src/scenes/scene0/sceneF.pic
git rm --cached RoadRad/src/scenes/scene0/sceneF.tiff
git rm --cached RoadRad/src/scenes/scene0/solid_yellow.rad
git rm --cached RoadRad/src/scenes/scene0/target.rad
git rm --cached RoadRad/src/scenes/scene0/target_0.rad
git rm --cached RoadRad/src/scenes/scene0/target_1.rad
git rm --cached RoadRad/src/scenes/scene0/target_10.rad
git rm --cached RoadRad/src/scenes/scene0/target_11.rad
git rm --cached RoadRad/src/scenes/scene0/target_12.rad
git rm --cached RoadRad/src/scenes/scene0/target_13.rad
git rm --cached RoadRad/src/scenes/scene0/target_2.rad
git rm --cached RoadRad/src/scenes/scene0/target_3.rad
git rm --cached RoadRad/src/scenes/scene0/target_4.rad
git rm --cached RoadRad/src/scenes/scene0/target_5.rad
git rm --cached RoadRad/src/scenes/scene0/target_6.rad
git rm --cached RoadRad/src/scenes/scene0/target_7.rad
git rm --cached RoadRad/src/scenes/scene0/target_8.rad
git rm --cached RoadRad/src/scenes/scene0/target_9.rad
git rm --cached RoadRad/src/scenes/scene0/test
git rm --cached RoadRad/src/scenes/scene0/test.pic
